### ISSUE TITLE
create buildroot environment

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#100]
It seems, too many freedos users run it under
qemu or virtualbox. Currently we do not cover
that user-base, as fdpp only runs on dosemu2
and people from freedos-32 or NightKernel do
fsck (were not interested in adopting fdpp on
their kernels).
We don't need these projects to prove that we
are the real power. :) Instead, we can create
the buildroot environment to provide the images
for qemu and vbox users.
@andrewbird @jschwartzenberg @stuaxo
do any of you want to play with that idea?
Might be an interesting experience and something
worth a line or 2 in your CV (buildroot is used
in many IT companies).
The DOS world should consist only of fdpp, so
lets push the 16bit competitors aside a little bit. :)

**Comment by stsp** [comment]
https://gist.github.com/anthonygclark/444f7c569c7b414c36c7c05714ea4a1e
This script creates qemu images from buildroot.

**Comment by stsp** [comment]
I'll send $200 to anyone who does that.

**Comment by stuaxo** [comment]
Link to buildroot, assuming I'm not the only person who's heard of it here for the first time -

https://buildroot.org/

**Comment by stsp** [comment]
@skitt What is the package name of buildroot in
debian and ubuntu (and fedora)? I really tried to
google for that (I mean, really-really! :), but googling
for buildroot gives you anything but what you need...
rpmbuild, dpkg-buildroot and all that.

**Comment by skitt** [comment]
@stsp I’m not 100% sure this is what you’re after, but the chroot-based build packages in Debian are `sbuild` and `pbuilder`/`cowbuilder`, with `debootstrap` to build chroots. In the RPM world, it’s `mock`.

**Comment by stsp** [comment]
No, I am after https://buildroot.org.
It provides the cross-build environment.
I think what you mention is to build debian
itself, which is buildroot not for.

**Comment by skitt** [comment]
Ah, right; as far as I’m aware buildroot isn’t packaged. It’s really designed to run from the unpacked tarball, or repository clone, without needing any installation.

**Comment by stsp** [comment]
> It’s really designed to run from the unpacked tarball, 

Indeed, but how about `Build-Depends`?
If its not packaged, it can't be build-depended.
Then how would the one build the package with
qemu images created with buildroot?

**Comment by stsp** [comment]
But that's not fatal of course.
No build-depend is not a big problem.
Someone just have to do that work...

**Comment by jschwartzenberg** [comment]
Are people using FreeDOS with buildroot?

Which bootloaders can load fdpp? Does it make sense to use either grub(2) or grub4dos?

**Comment by stsp** [comment]
> Are people using FreeDOS with buildroot?

Buildroot is not for users. Its for developers to
build their project into a minimal root fs.

> Which bootloaders can load fdpp?

Not many, but fdpp-buildroot, as you may guess,
can be loaded by anything. The script I referred
above, uses grub.

**Comment by stsp** [comment]
buildroot provides yasm instead of nasm
(easy to work-around) and gcc instead of
clang (not easy to work-around).
Sigh.

**Comment by stsp** [comment]
yasm problem worked around.
But does anyone know how to build fdpp
with gcc tool-chain? :(
Not that I care about gcc these days, but
buildroot does.

**Comment by stsp** [comment]
buildroot devs confirmed that clang tool-chain
is unsupported, and, while some work is ongoing,
its not a top priority and no any estimated dates.
The externally built cross clang is also unsupported.
Trying to feed it to buildroot by hands is a very
challenging task right now, according to the devs. :(

**Comment by stsp** [comment]
clang support in buildroot, presentation:
https://www.youtube.com/watch?v=j-BtL8IVaLg

**Comment by stsp** [comment]
Romain Naour (buildroot dev) says that
an explicit override is possible, like this:
```
LIBCEF_TARGET_CONFIGURE_ENV = \
	$(TARGET_MAKE_ENV) \
	BUILD_CC="clang" \
	BUILD_CXX="clang++" \
	CC="clang" \
	CXX="clang++"
```

Worth a try.

**Comment by stsp** [comment]
I started a buildroot project here:
https://github.com/dosemu2/fdpp-buildroot
It doesn't do much yet, but can be
built. :)
Help appreciated!

**Comment by andrewbird** [comment]
I'm unfamiliar with buildroot with qemu-kvm, though I think in a long distant past I may have used buildroot with OpenWRT. So what's on the output disk.img: dosemu2 + fdpp + minimal linux distro that qemu-kvm can load, or is it something else?

**Comment by stsp** [comment]
So far there is just linux with uclibc.
Other components are only sketched,
and I have no idea will dosemu2 work
with uclibc or not.
Ideally there should be some stripped
down version of dosemu2 that can only
load fdpp, pass-through vga and grab
the nic. It should also have some dynamic
drives management to handle flashes.

**Comment by stsp** [comment]
After a week of work, I've
got to the point where I need
comcom32. But it seems you
haven't switched comcom32
from travis yet.
And even if you do - will there
be a stable URL to get the latest
comcom32 build from?
As building comcom32 within
buildroot is not the best idea.

**Comment by andrewbird** [comment]
Ahh, okay I'll swap that now.

I can do a stable name, but when I did it before it had to be uploaded to a release (I created one on the fly, but that doesn't seem ideal here). I'll see if there's an alternative.

**Comment by stsp** [comment]
Perhaps just uploading the result
to some other server will help.

**Comment by andrewbird** [comment]
>Perhaps just uploading the result
to some other server will help.

Yes, but the login credentials could be difficult to keep secret.

I looked at a few other projects, and they seem to have a `latest-ci-build` release whose artefact gets overwritten.

**Comment by stsp** [comment]
> Yes, but the login credentials could be difficult to keep secret.

anonymous:-@ftp://some_ftp :)

> I looked at a few other projects, and they seem to have a latest-ci-build release whose artefact gets overwritten.

Sounds good.

**Comment by stsp** [comment]
It appears that UEFI may
not map the VGA bios:
https://news.ycombinator.com/item?id=20389688
And even if it does, it definitely
is not supported by a boot loaders:
https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1711452

This all means the one can't
switch to VGA text mode.
So it seems like the idea of
having a stripped down dosemu
to just boot fdpp, doesn't work.
You need the whole dosemu2,
with SDL on top of KMS, with
TTF and all that.
And I suppose people will then
ask "so why not dosbox"...
Seems there is no way to get
fdpp working with a "thin" layer
on top of UEFI.

**Comment by stuaxo** [comment]
I guess those legacy UEFIs will work that are mentioned at the end, but hardly future proof.

**Comment by stsp** [comment]
This is not supported by grub,
so no way to switch to text mode
anyway (w/o grub patching).

**Comment by stsp** [comment]
Buildroot finally works.
Everyone is invited to test the
slowest DOS in the world. :)
It takes about 50 seconds to
get from qemu startup to the
fully functional NDN.
The main reason is that sdl2
doesn't have the fb support,
so instead it utilizes the
kms_swrast on top of mesa
on top of bochs_drm on top
of qemu... And I had to use
sdl from git to get to even that.
All currently known sdl2
releases do not work under
bochs_drm at all.

**Comment by stsp** [comment]
Andrew, would you like to
make a github integration
so that the built image can
be downloaded?
But it should be built not
per-commit, but rather on
demand. As otherwise it
will drain the entire build
band-width that github
assigns to us.

**Comment by stuaxo** [comment]
Could directfb help here ?

**Comment by stsp** [comment]
directfb is considered legacy too:
https://discourse.libsdl.org/t/is-anyone-using-directfb/22616
But seems like sdl still has it in,
and in fact it got some commits
last year, so it seems people
started to resurrect it.

So please try that and let us know! :)

**Comment by stuaxo** [comment]
I'm willing to try it as-is, as a start... 

I cloned the fdpp-buildroot repo, I guess I need to install some things (buildroot?), before running any of the scripts ?

**Comment by stsp** [comment]
No, it should just work.
At worst, you'll get the error
from scripts if something is
missing.

**Comment by stuaxo** [comment]
I tried running them, here is the output for each:
```
$ ./build.sh
make: *** buildroot: No such file or directory. Stop.
make: *** buildroot: No such file or directory. Stop.
$ ./make.sh 
make: *** buildroot: No such file or directory. Stop.
$ ./run.sh
qemu-system-x86_64: -hda buildroot/output/images/disk.img: Could not open 'buildroot/output/images/disk.img': No such file or directory
```

**Comment by stuaxo** [comment]
Ah, I guess I need to grab the other projects and check them out in the fdpp-buildroot directory ?   Or are these maybe git subprojects ?

**Comment by andrewbird** [comment]
`git submodule update`

**Comment by stsp** [comment]
These are sub-projects, but these
sub-modules drives me nuts.
`git submodule update`
doesn't work for me now, too...

**Comment by andrewbird** [comment]
`.gitignore`

**Comment by stsp** [comment]
No.
Fixing it now...

**Comment by stsp** [comment]
Please try again.
It seems submodules do not
just reside in a .gitmodules
file. They need some special
objects to be committed, that
do not relate to any files in the
repo.

**Comment by stsp** [comment]
And it seems you need to
commit/push all updates
to sub-modules, to your
master. As these special
objects seems to record
the commit hash of a
sub-module, and use only
that.

**Comment by andrewbird** [comment]
`git clone --recurse-submodules https://github.com/dosemu2/fdpp-buildroot.git` works for me now, as does `git submodule status`

**Comment by stsp** [comment]
Yes, it now works.
I did those special "submodule commits".
Try to do that on revision 268838ee
or before.

**Comment by stsp** [comment]
Not sure why can't we have
every project on its master.
Why should I commit every
new update in sub-module?
That looks counter-productive.

**Comment by stuaxo** [comment]
Wow, quite a lot of building, is it worth enabling ccache ?

**Comment by andrewbird** [comment]
Sorry I just deleted it, working on something else at the moment. Maybe later...

**Comment by stsp** [comment]
> Wow, quite a lot of building, is it worth enabling ccache ?

Not sure really.
buildroot itself keeps the
built files and doesn't rebuild
them, unless you remove the
buildroot itself and start from
scratches.
With ccache, even removing
buildroot won't purge the cache.
But is it a big advantage?
Are you going to remove buildroot
every time?

> Sorry I just deleted it, working on something else at the moment. Maybe later...

Muahaha!
Well, quite a good answer
to my question above. :)
Do you have a time machine
or what? :)

**Comment by stuaxo** [comment]
Wow, haven't built anything that took that long in a while... OK, maybe I didn't quite this time..

```
$ ./build.sh
....[snipped]....
  INSTALL net/netfilter/xt_nat.ko
  DEPMOD  5.11.8
# Installing dtc (device tree compiler) as host tool, if selected
if grep -q "CONFIG_DTC=y" /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/linux-5.11.8/.config; then /usr/bin/install -D -m 0755 /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/linux-5.11.8/scripts/dtc/dtc /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/linux-dtc ; ln -sf linux-dtc /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/dtc; fi
>>> linux 5.11.8 Installing to images directory
/usr/bin/install -m 0644 -D /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/linux-5.11.8/arch/x86/boot/bzImage /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/images/bzImage
>>> comcom32 custom Syncing from source dir /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/comcom32
rsync -au --chmod=u=rwX,go=rX  --exclude .svn --exclude .git --exclude .hg --exclude .bzr --exclude CVS /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/comcom32/ /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/comcom32-custom
>>> comcom32 custom Configuring
>>> comcom32 custom Building
cd /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/comcom32 && curl -O https://dosemu2.github.io/comcom32/files/comcom32.zip && unzip comcom32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  105k  100  105k    0     0   571k      0 --:--:-- --:--:-- --:--:--  571k
Archive:  comcom32.zip
  inflating: comcom32.exe            
>>> comcom32 custom Installing to target
/usr/bin/make -j9 -C /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/comcom32-custom install DESTDIR=/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/target PREFIX=/usr
Build it first!
make[2]: *** [Makefile:43: install] Error 1
make[1]: *** [package/pkg-generic.mk:341: /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/comcom32-custom/.stamp_target_installed] Error 2
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot'
```

**Comment by stsp** [comment]
Should now be fixed.
Don't worry, you won't
have to re-build everything
again.
But we might indeed need
ccache in the future. Not
only because Andrew always
erases buildroot. but also
because that might be helpful
with github and other build
farms.

**Comment by stuaxo** [comment]
I did `git pull` `git submodule sync` `git submodule update` but it still doesn't seem to work:

```
./make.sh           
make: Entering directory '/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot'
>>> comcom32 custom Installing to target
/usr/bin/make -j9 -C /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/comcom32-custom install DESTDIR=/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/target PREFIX=/usr
Build it first!
make[2]: *** [Makefile:43: install] Error 1
make[1]: *** [package/pkg-generic.mk:341: /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/comcom32-custom/.stamp_target_installed] Error 2
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot'

```

**Comment by stsp** [comment]
You need to do
`./make.sh comcom32-dirclean`.
buildroot doesn't update things
automatically.

**Comment by stsp** [comment]
Have you built a thing?

**Comment by stuaxo** [comment]
I left it going and when I came back it had got a lot further, but not quite all the way:

(I tried this, and then tried again with `./make.sh clean` first

```
...
E64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -o remap.o remap.c
rm -f ../../../../2012.11-20210412/lib/libbase_dev_vga.a
ar cr ../../../../2012.11-20210412/lib/libbase_dev_vga.a miscemu.o vgaemu.o vesa.o dacemu.o attremu.o seqemu.o crtcemu.o gfxemu.o hercemu.o vgafonts.o vesabios_pm.o vesabios.o
/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/x86_64-buildroot-linux-gnu-ranlib ../../../../2012.11-20210412/lib/libbase_dev_vga.a
rm -f ../../../2012.11-20210412/lib/libbase_kbd_unicode.a
ar cr ../../../2012.11-20210412/lib/libbase_kbd_unicode.a serv_xlat.o serv_backend.o keymaps.o keyb_raw.o getfd.o keyb_clients.o prestroke.o keyb_none.o keyboard.o dosemu_keys.o keynum.o
/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/x86_64-buildroot-linux-gnu-ranlib ../../../2012.11-20210412/lib/libbase_kbd_unicode.a
rm -f ../../../2012.11-20210412/lib/libbase_misc.a
ar cr ../../../2012.11-20210412/lib/libbase_misc.a hma.o ioctl.o disks.o utilities.o dos2linux.o fatfs.o mmio_tracing.o
/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/x86_64-buildroot-linux-gnu-ranlib ../../../2012.11-20210412/lib/libbase_misc.a
rm -f ../../../2012.11-20210412/lib/libbase_video.a
ar cr ../../../2012.11-20210412/lib/libbase_video.a text.o render.o video.o instremu.o remap.o
/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/host/bin/x86_64-buildroot-linux-gnu-ranlib ../../../2012.11-20210412/lib/libbase_video.a
make[2]: *** [Makefile:29: default] Error 2
make[1]: *** [package/pkg-generic.mk:250: /home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot/output/build/dosemu2-custom/.stamp_built] Error 2
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/home/stu/projects/external/dosemu2-projects/fdpp-buildroot/buildroot'
```

I might have to wait until after 9pm tomorrow to try again as I need to use the computer for work related dev work during the day (though may be able sneak in the odd build).

**Comment by stsp** [comment]
Should now be fixed.
Please try whenever you can, no hurry. :)

**Comment by stuaxo** [comment]
OK, seems to have built .. just need to get things running now...

```
$ ./run.sh  
WARNING: Image format was not specified for 'buildroot/output/images/disk.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu: could not load PC BIOS '/usr/share/edk2/ovmf/OVMF_CODE.fd'
```

**Comment by stuaxo** [comment]
Ah, the file it wants is `/usr/share/OVMF/OVMF_CODE.fd` and it boots !

![image](https://user-images.githubusercontent.com/179677/114766437-4d0b3980-9d5e-11eb-9e44-f5bf9a48c0dc.png)

**Comment by stuaxo** [comment]
It's as slow as advertised :)

I thought I'd see what happens if I enabled virgil by adding `-vga virtio -display gtk,gl=on`, everything is much quicker - but I think it's because things are failing as opposed to virgil working.


https://user-images.githubusercontent.com/179677/114774377-0a4e5f00-9d68-11eb-994c-9a30415c733e.mp4

(also.. enjoying the side effect of having it boot into NDN, so when you exit dosemu to the shell then exit again you come back to DOS)

**Comment by stsp** [comment]
Yes, things are failing.
You booted into `-t` mode which
I left enabled for debugging.

**Comment by stsp** [comment]
Btw, congrats for being the
first person in the world to
boot DOS from UEFI. :)

**Comment by stuaxo** [comment]
So, in theory if the virtual machine could use Virgil, and dosemu ran using SDL2 renderer things could speed up ?

I guess what I'd need to work out is how to bring up Virgil in the qemu VM first.

**Comment by stsp** [comment]
> So, in theory if the virtual machine could use Virgil, and dosemu ran using SDL2 renderer things could speed up ?

Very unlikely.
I think virgil is a frame-work
to pass-through the 3d rendering
over virtio-gpu, whereas otherwise
virtio-gpu is mostly a 2d pass-through
thing.
You can try directfb though.

**Comment by stuaxo** [comment]
Is the aim for buildroot, to make a minimal distro that boots into DOSEMU2, so the main users will use this on real computers ?

**Comment by stsp** [comment]
I don't know myself for a moment.
The original idea was to boot fdpp
and using dosemu2 only as a loader.
But since text mode VGA is not
possible with UEFI, that turned into
a "minimal distro for dosemu2". In
which case the one can ask "why
not dosbox".
But we'll see.
Maybe eventually it will be
suitable for freedos users.

**Comment by stsp** [comment]
I thought a bit about using vfat
instead of ext4, to make the thing
more dosish.
We could have entire buildroot
image as fdppio.sys on vfat, but
I suppose its going to be insecure
and unreliable, as all the fs checks
can be bypassed by altering image
directly, or just erasing it will crash
the system.
Well, at least the drive_c partition
can be on vfat, but I am not sure
if OFD locks would work. No OFD
locks mean no region locking in
DOS, and, more importantly, no
share modes.
Andrew, do you know if vfat supports
OFD locks?
If not, we might need to write the
lock manager after all.

**Comment by stsp** [comment]
I thought a bit about using vfat
instead of ext4, to make the thing
more dosish.
We could have entire buildroot
image as fdppio.sys on vfat, but
I suppose its going to be insecure
and unreliable, as all the fs checks
can be bypassed by altering image
directly, or just erasing it will crash
the system.
Well, at least the drive_c partition
can be on vfat, but I am not sure
if OFD locks would work. No OFD
locks mean no region locking in
DOS, and, more importantly, no
share modes.
Andrew, do you know if vfat supports
OFD locks?
If not, we might need to write the
lock manager after all.
