### ISSUE TITLE
alpha waves doesn't work

### ISSUE THREAD

**Issue by stsp** [dosemu2/fdpp#112]
**Describe the bug**
Hangs at start.
Works on 1.4.

**To Reproduce**
Just start.

**Attach the binaries or provide an URL**
http://www.abandonia.com/en/games/25594/Alpha+Waves.html

Almost no games seem to work.
Testing more looks like the waste of time.

**Comment by stsp** [comment]
It actually still doesn't work properly.
It says ` Please insert the disk labeled ALPHA WAVES DISK 1 in the current drive.`
but works under PC-DOS.
Something FS-related, Andrew, want
to debug this?

**Comment by andrewbird** [comment]
okay will do.

**Comment by andrewbird** [comment]
Under FDPP when the program tries to reopen the `progs.cc1` file int21/3d returns with CF set and AX=04 which I believe is no file handles available. I tried setting FILES=50 in config.sys but it made no difference.

**Comment by stsp** [comment]
fdpp has by default FILES=64

**Comment by andrewbird** [comment]
A couple of futher data points
- Doesn't seem like it's an MFS problem as it's reproducible on FAT16
- FreeDOS 1.20 crashes on both MFS and FAT16 with
~~~
Real-mode state dump:
EIP: 0000:00000018 ESP: 0056:00000006  VFLAGS(b): 01011 00000010 01000110
EAX: 00000000 EBX: 00000000 ECX: 00000000 EDX: 0000005c VFLAGS(h): 000b0246
ESI: 00000000 EDI: 00000000 EBP: 00000000 DS: 0000 ES: 1b80 FS: 0000 GS: 0000
FLAGS: PF ZF IF RF VM VIF  IOPL: 0
STACK: 00 00 00 00 00 00 00 00 80 1b -> 00 00 00 00 00 00 00 00 00 00 
OPS  : d8 00 06 f1 00 f0 07 f1 00 f0 -> c7 11 d8 00 09 f1 00 f0 0f 00 
	c711d800            0000:0018 mov  word [bx+di],00D8
~~~

**Comment by stsp** [comment]
If its really a result of int21/3d failure, must
be quite easy to follow with gdb, or?

**Comment by andrewbird** [comment]
Not sure why I can't get GDB to run properly
~~~
(gdb) run
Starting program: /clients/common/dosemu2.git/2.0-pre8/bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRW\# -o test.log --Fimagedir /clients/common/dosemu2.git/test-imagedir --Flibdir /clients/common/dosemu2.git/test-libdir -I \'cpuemu vm86sim cpu_vm emulated\'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
warning: Error reading shared library list entry at 0x7670
warning: Error reading shared library list entry at 0x9d0
warning: Error reading shared library list entry at 0xffffea50
warning: Error reading shared library list entry at 0xffffffb0
warning: Error reading shared library list entry at 0xffffc280
[New Thread 0xb1d19b40 (LWP 24833)]
[New Thread 0xa4ef1b40 (LWP 24834)]
[New Thread 0xa42f0b40 (LWP 24835)]
warning: Error reading shared library list entry at 0xffff9b60
warning: Error reading shared library list entry at 0xffff8540
warning: Error reading shared library list entry at 0x90
warning: Error reading shared library list entry at 0x3e0
[New Thread 0x93aefb40 (LWP 24836)]
[New Thread 0x838ffb40 (LWP 24838)]
warning: Error reading shared library list entry at 0x5d80
ERROR: Your fluidsynth is too old and soundfonts not found
warning: Error reading shared library list entry at 0xffffb210
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
[New Thread 0x8287ab40 (LWP 24840)]
INFO: booting with comcom32, this is very experimental
INFO: fdpp booting, this is very experimental!

Thread 1 "dosemu.bin" received signal SIGUSR1, User defined signal 1.
0xb7fd7a7d in __kernel_vsyscall ()
(gdb) cont
Continuing.
Cannot find user-level thread for LWP 24804: generic error
~~~

I do this so infrequently, did I miss something?

**Comment by stsp** [comment]
Try `handle SIGUSR1 nostop noprint`.
I've seen such problem on 32bit systems,
I don't think they are properly maintained
these days.

Anyway, the problem is that the game
crates new PSP with func 26, which sets
parent_psp to 0. Then it uses func 0x50
to activate that PSP, and 0x31 to TSR it
(hell knows why). The problem is that 0
in parent_psp makes it into a current psp
on 0x31, which results in a junk in PSP,
hence the corrupted JFT and no free
handles.
Not sure what fix can fix that.

**Comment by stsp** [comment]
I applied a few patches to make this game
tracible with dosdebug. It uses some anti-debugger
tricks, which fooled our dosdebug.
It seems, this playing with PSP is also a part
of anti-debugging protection, because you can
set the breakpoint (in gdb) to int 1 vector, and
you'll see that the game alters it exactly before
playing with PSP, and restores immediately after.
This makes it very easy to get into a problematic
spot. We only need to start tracing after it altered
int 1.

**Comment by stsp** [comment]
Yep, it is an anti-debugger trick.
If I trace it under PC-DOS, then it also
says "please insert disk", just like under
fdpp. However, PC-DOS doesn't seem
to set parent_psp to 0 by fn 0x26:
```
INT 0x21, system state: emulated,stopped in real mode while in DPMI
AX=2650  BX=1b54  CX=c000  DX=0ba3  SI=09e3  DI=039f  SP=19ac  BP=091c
DS=09e3  ES=09e3  FS=543d  GS=7548  FL=000b3202
CS:IP=09e3:0dfc       SS:SP=09e3:19ac

09e3:0dfc CD21             int  21
dosdebug> t
dosdebug> 
system state: emulated,stopped in real mode while in DPMI
AX=26f0  BX=1b54  CX=c000  DX=0ba3  SI=09e3  DI=039f  SP=19ac  BP=091c
DS=09e3  ES=09e3  FS=543d  GS=7548  FL=000b3302
CS:IP=09e3:0dfe       SS:SP=09e3:19ac

09e3:0dfe BA8000           mov  dx,0080
dosdebug> d ba3:0
dosdebug> 

0ba3:0000 CD 20 F4 F4 F4 9A F0 FE 1D F0 EC 01 8B 09 0F F5  M ttt.p~.pl....u
0ba3:0010 00 F0 85 15 E3 09 F4 F4 06 7E 05 00 E8 9E 05 72  .p..c.tt.~..h..r
0ba3:0020 20 8D 77 1A E8 4F FD 73 06 B8 20 00 F4 F4 F4 F4   .w.hO}s.8 .tttt
0ba3:0030 F4 F4 14 00 18 00 A3 0B FF FF FF FF F4 F4 F4 F4  tt....#.tttt
0ba3:0040 07 00 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  ..tttttttttttttt
0ba3:0050 CD 21 CB F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  M!Kttttttttttttt
0ba3:0060 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  tttttttttttttttt
0ba3:0070 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  tttttttttttttttt
```

**Comment by stsp** [comment]
So it seems PC-DOS just doesn't zero
out parent_psp, keeping it as it.
But RBIL says it should be zeroed.
Andrew, would you like to test some DOSes
on that?

Note: by not zeroing parent_psp I am able
to avoid the "please insert disk" error, but
it still doesn't work.

**Comment by stsp** [comment]
Try `$_cpu_vm_dpmi="kvm"` to avoid gdb problems.

**Comment by andrewbird** [comment]
> I've seen such problem on 32bit systems,
I don't think they are properly maintained
these days.

Yes, I'm getting pretty fed up with 32 bit support on Ubuntu. I even had Dosemu/FDPP/Alphawaves reboot my machine, which I can only guess means they've screwed up `vm86()` again. Spotify doesn't work any more due to an incorrect library version which they refuse to fix in 32 bit, that's their problem I know, but it's probably time I joined the herd on 64 bit.

Well done on tracking down the PSP/JFT issue, I doubt I'd have got to that.

> Try `$_cpu_vm_dpmi="kvm"` to avoid gdb problems.

Yes that fixed FDPP startup for me, so I've added it to my personal startup script, thanks.

> So it seems PC-DOS just doesn't zero
out parent_psp, keeping it as is.
But RBIL says it should be zeroed.
Andrew, would you like to test some DOSes
on that?

I'll try to write a test for that, but I'm sorry it probably won't be today.

**Comment by stsp** [comment]
If there is a reboot, you need to
create a minimal test-case and we'll
call our friend Andy Lutomirski for help.
But no one will fix gdb on 32bits for sure.
You can also try lldb, but I dont think
its going to be much better.

**Comment by stsp** [comment]
Btw, the psp I dumped above, seems
to be severely corrupted. It all is
overwritten with F4s. It happens only
under dosdebug. Either some
anti-debugger trick works, or some bug.

**Comment by andrewbird** [comment]
I started to write a little test program to find the behaviour of all the DOSes I have, but I don't see the non-zeroed parent_psp field that you mention.

Here's the program
```asm
.text
.code16

    .globl  _start16
_start16:

# designate target segment
    push    %cs
    pop     %ax
    addw    $0x0200, %ax
    movw    %ax, %es

# create PSP in memory
    movw    %es, %dx
    movw    $0x2600, %ax
    int     $0x21

# see what the parent PSP is set to
    movw    $0x0016, %di
    cmpw    $0x0000, %es:(%di)
    je      success

cmpfail:
    movb    $0x9, %ah
    movw    $cmpfailmsg, %dx
    int     $0x21
    jmp     exit

success:
    movb    $0x9, %ah
    movw    $successmsg, %dx
    int     $0x21
    jmp     exit

exit:
    movb    $0x4c, %ah
    int     $0x21

cmpfailmsg:
    .ascii  "PSP is not zero\r\n$"
successmsg:
    .ascii  "PSP is zero\r\n$"
```

I'm seeing that all the DOSes here zero the parent_psp field
~~~
Test DR-DOS-3.40 Create New PSP                                                  ... ok
Test DR-DOS-3.41 Create New PSP                                                  ... ok
Test DR-DOS-5.00-900615 Create New PSP                                           ... ok
Test DR-DOS-5.00-900814 Create New PSP                                           ... ok
Test DR-DOS-6.00-930319 Create New PSP                                           ... ok
Test DR-DOS-6.00 Create New PSP                                                  ... ok
Test DR-DOS-7.00 Create New PSP                                                  ... ok
Test DR-DOS-7.01 Create New PSP                                                  ... ok
Test DR-DOS-7.02-971119 Create New PSP                                           ... ok
Test DR-DOS-7.02-980123 Create New PSP                                           ... ok
Test DR-DOS-7.03 Create New PSP                                                  ... ok
Test DR-DOS-8.00 Create New PSP                                                  ... ok
Test FR-DOS-1.20 Create New PSP                                                  ... ok
Test MS-DOS-3.10 Create New PSP                                                  ... ok
Test MS-DOS-3.20 Create New PSP                                                  ... ok
Test MS-DOS-3.21 Create New PSP                                                  ... ok
Test MS-DOS-3.30-Nec Create New PSP                                              ... ok
Test MS-DOS-3.30 Create New PSP                                                  ... ok
Test MS-DOS-3.31 Create New PSP                                                  ... ok
Test MS-DOS-4.01 Create New PSP                                                  ... ok
Test MS-DOS-5.00 Create New PSP                                                  ... ok
Test MS-DOS-6.00 Create New PSP                                                  ... ok
Test MS-DOS-6.20 Create New PSP                                                  ... ok
Test MS-DOS-6.21 Create New PSP                                                  ... ok
Test MS-DOS-6.22 Create New PSP                                                  ... ok
Test MS-DOS-7.00 Create New PSP                                                  ... ok
Test MS-DOS-7.10 Create New PSP                                                  ... ok
Test PC-DOS-3.00-Compaq Create New PSP                                           ... ok
Test PC-DOS-3.00 Create New PSP                                                  ... ok
Test PC-DOS-3.10-850307 Create New PSP                                           ... ok
Test PC-DOS-3.10-850422 Create New PSP                                           ... ok
Test PC-DOS-3.10-Compaq Create New PSP                                           ... ok
Test PC-DOS-3.20-851230 Create New PSP                                           ... ok
Test PC-DOS-3.20-860221 Create New PSP                                           ... ok
Test PC-DOS-3.30 Create New PSP                                                  ... ok
Test PC-DOS-3.31-Compaq Create New PSP                                           ... ok
Test PC-DOS-4.00 Create New PSP                                                  ... ok
Test PC-DOS-4.01 Create New PSP                                                  ... ok
Test PC-DOS-5.00 Create New PSP                                                  ... ok
Test PC-DOS-5.02 Create New PSP                                                  ... ok
Test PC-DOS-6.10 Create New PSP                                                  ... ok
Test PC-DOS-6.30 Create New PSP                                                  ... ok
Test PC-DOS-7.00 Create New PSP                                                  ... ok
Test PC-DOS-7.10 Create New PSP                                                  ... ok
Test PC-DOS-7.2K Create New PSP                                                  ... ok
Test PP-DOS-GIT Create New PSP                                                   ... ok
~~~

Here's dosdebug running against FreeDOS 1.20, notice now the PSP is only partially populated
```asm
system state: stopped
AX=0000  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2382  FS=0000  GS=0000  FL=000a3346
CS:IP=2382:0100       SS:SP=2382:fffe

2382:0100 0E               push cs
dosdebug> t
dosdebug> 
system state: stopped
AX=0000  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffc  BP=0000
DS=2382  ES=2382  FS=0000  GS=0000  FL=000a3346
CS:IP=2382:0101       SS:SP=2382:fffc

2382:0101 58               pop  ax
dosdebug> 
dosdebug> 
system state: stopped
AX=2382  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2382  FS=0000  GS=0000  FL=000a3346
CS:IP=2382:0102       SS:SP=2382:fffe

2382:0102 050002           add  ax,0200
dosdebug> 
dosdebug> 
system state: stopped
AX=2582  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2382  FS=0000  GS=0000  FL=000a3306
CS:IP=2382:0105       SS:SP=2382:fffe

2382:0105 8EC0             mov  es,ax
dosdebug> 
dosdebug> 
system state: stopped
AX=2582  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2582  FS=0000  GS=0000  FL=000a3306
CS:IP=2382:0107       SS:SP=2382:fffe

2382:0107 8CC2             mov  dx,es
dosdebug> 
dosdebug> 
system state: stopped
AX=2582  BX=0000  CX=0000  DX=2582  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2582  FS=0000  GS=0000  FL=000a3306
CS:IP=2382:0109       SS:SP=2382:fffe

2382:0109 B80026           mov  ax,2600
dosdebug> d es:0000
dosdebug> 

2582:0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
dosdebug> t
dosdebug> 
system state: stopped
AX=2600  BX=0000  CX=0000  DX=2582  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2582  FS=0000  GS=0000  FL=000a3306
CS:IP=2382:010c       SS:SP=2382:fffe

2382:010c CD21             int  21
dosdebug> t
dosdebug> 
system state: stopped
AX=2600  BX=0000  CX=0000  DX=2582  SI=0000  DI=0000  SP=fffe  BP=0000
DS=2382  ES=2582  FS=0000  GS=0000  FL=00083306
CS:IP=2382:010e       SS:SP=2382:fffe

2382:010e BF0000           mov  di,0000 # earlier version of my test program!

dosdebug> d es:0000
dosdebug> 

2582:0000 00 00 00 00 00 00 00 00 00 00 E7 F6 00 F0 C6 07  ..........gv.pF.
2582:0010 B2 10 47 02 C2 10 00 00 00 00 00 00 00 00 00 00  2.G.B...........
2582:0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2582:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................

dosdebug> d cs:0000 # our original PSP
dosdebug> 

2382:0000 CD 20 EF 9F 00 9A F0 FE 1D F0 E7 F6 00 F0 C6 07  M o...p~.pgv.pF.
2382:0010 B2 10 47 02 C2 10 B2 10 01 01 01 00 02 FF FF FF  2.G.B.2......
2382:0020 FF FF FF FF FF FF FF FF FF FF FF FF 74 23 E0 FF  t#`
2382:0030 82 23 14 00 18 00 82 23 00 00 B2 10 00 00 00 00  .#.....#..2.....
2382:0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
2382:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
2382:0060 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
2382:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00          ........
```

**Comment by andrewbird** [comment]
I just modified the test to check for `CD20` at beginning of PSP, only FreeDOS 1.20 and FDPP don't populate this
~~~
Test DR-DOS-3.40 Create New PSP                                                  ... ok
Test DR-DOS-3.41 Create New PSP                                                  ... ok
Test DR-DOS-5.00-900615 Create New PSP                                           ... ok
Test DR-DOS-5.00-900814 Create New PSP                                           ... ok
Test DR-DOS-6.00-930319 Create New PSP                                           ... ok
Test DR-DOS-6.00 Create New PSP                                                  ... ok
Test DR-DOS-7.00 Create New PSP                                                  ... ok
Test DR-DOS-7.01 Create New PSP                                                  ... ok
Test DR-DOS-7.02-971119 Create New PSP                                           ... ok
Test DR-DOS-7.02-980123 Create New PSP                                           ... ok
Test DR-DOS-7.03 Create New PSP                                                  ... ok
Test DR-DOS-8.00 Create New PSP                                                  ... ok
Test FR-DOS-1.20 Create New PSP                                                  ... FAIL
Test MS-DOS-3.10 Create New PSP                                                  ... ok
Test MS-DOS-3.20 Create New PSP                                                  ... ok
Test MS-DOS-3.21 Create New PSP                                                  ... ok
Test MS-DOS-3.30-Nec Create New PSP                                              ... ok
Test MS-DOS-3.30 Create New PSP                                                  ... ok
Test MS-DOS-3.31 Create New PSP                                                  ... ok
Test MS-DOS-4.01 Create New PSP                                                  ... ok
Test MS-DOS-5.00 Create New PSP                                                  ... ok
Test MS-DOS-6.00 Create New PSP                                                  ... ok
Test MS-DOS-6.20 Create New PSP                                                  ... ok
Test MS-DOS-6.21 Create New PSP                                                  ... ok
Test MS-DOS-6.22 Create New PSP                                                  ... ok
Test MS-DOS-7.00 Create New PSP                                                  ... ok
Test MS-DOS-7.10 Create New PSP                                                  ... ok
Test PC-DOS-3.00-Compaq Create New PSP                                           ... ok
Test PC-DOS-3.00 Create New PSP                                                  ... ok
Test PC-DOS-3.10-850307 Create New PSP                                           ... ok
Test PC-DOS-3.10-850422 Create New PSP                                           ... ok
Test PC-DOS-3.10-Compaq Create New PSP                                           ... ok
Test PC-DOS-3.20-851230 Create New PSP                                           ... ok
Test PC-DOS-3.20-860221 Create New PSP                                           ... ok
Test PC-DOS-3.30 Create New PSP                                                  ... ok
Test PC-DOS-3.31-Compaq Create New PSP                                           ... ok
Test PC-DOS-4.00 Create New PSP                                                  ... ok
Test PC-DOS-4.01 Create New PSP                                                  ... ok
Test PC-DOS-5.00 Create New PSP                                                  ... ok
Test PC-DOS-5.02 Create New PSP                                                  ... ok
Test PC-DOS-6.10 Create New PSP                                                  ... ok
Test PC-DOS-6.30 Create New PSP                                                  ... ok
Test PC-DOS-7.00 Create New PSP                                                  ... ok
Test PC-DOS-7.10 Create New PSP                                                  ... ok
Test PC-DOS-7.2K Create New PSP                                                  ... ok
Test PP-DOS-GIT Create New PSP                                                   ... FAIL
~~~

Any other fields you'd like me to check whilst I have the test available?

BTW I don't think there's any point in adding this test permanently to the suite, do you?

**Comment by stsp** [comment]
Its absolutely impossible that it doesn't
populate CD20. Please attach your test-case.

**Comment by andrewbird** [comment]
Will do later , In the meantime did you see the dosdebug dump of the new PSP above where Cd20 is not set?

**Comment by andrewbird** [comment]
Perhaps it's where I chose to place the new PSP in memory that's the problem?

**Comment by stsp** [comment]
Of course I've seen it, but its not possible.
Maybe location is the problem, but you put
it after the code, so I dont know what overwrites
it.

**Comment by stsp** [comment]
Oh wait, IIRC CS points to PSP and IP points
to 200, so you do not put it after the code, but
_over_ the code??

**Comment by andrewbird** [comment]
I thought I added 200 to segment not offset , but to be honest it was just a guess that it would be safe. I'd tried to allocate memory before using int21/48 but it failed with no more mem I think because I'm assembling to a .com.

**Comment by stsp** [comment]
You, so you added 8K, and then I don't know what fails.

**Comment by andrewbird** [comment]
Here's the test case for parent_psp == zero, easily modifiable to test start for CD20 [parentpspzero.zip](https://github.com/stsp/fdpp/files/3894243/parentpspzero.zip).

**Comment by andrewbird** [comment]
The CS passed to `new_psp()` is incorrect (under FDPP it's 0xf000) as it should be the caller's CS, consequently the `fmemcpy()` in `new_psp()` copies crap not the old PSP.

see kernel/inthndlr.c
```C
      /* Dos Create New Psp                                           */        
    case 0x26:                                                                  
      new_psp(lr.DX, r->CS);                                                    
      break;                                                                    
```

I tried using lr-CS, but it seems that lregs has no CS field, so how should I get the caller's CS?

**Comment by andrewbird** [comment]
Since I have a `.com` file for the test I temporarily swapped the `r->CS` for `lr.DS` in the call to `new_psp()` and now the new psp is populated properly.
~~~
dosdebug> d es:0000
dosdebug> 

0f09:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E7 F6 00 F0 0F F5  M . ..p~.pgv.p.u
0f09:0010 00 F0 11 F5 00 F0 00 00 01 01 01 00 02 FF FF FF  .p.u.p.......
0f09:0020 FF FF FF FF FF FF FF FF FF FF FF FF F9 0C E0 FF  y.`
0f09:0030 09 0D 14 00 18 00 09 0D 00 00 F0 07 00 00 00 00  ..........p.....
0f09:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0f09:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
0f09:0060 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
0f09:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00          ........
~~~

**Comment by andrewbird** [comment]
Doing this gives proper PSP data.
```C
commit bafae8f5dd18332b615ea9ec091ab295705b6bcd (HEAD -> newpsp01)
Author: Andrew Bird <ajb@spheresystems.co.uk>
Date:   Wed Nov 27 12:25:01 2019 +0000

    inthndlr.c: Pass the user's CS to new_psp()

diff --git a/kernel/inthndlr.c b/kernel/inthndlr.c
index 8a6c5de..18d8cad 100644
--- a/kernel/inthndlr.c
+++ b/kernel/inthndlr.c
@@ -681,7 +681,7 @@ dispatch:
 
       /* Dos Create New Psp                                           */
     case 0x26:
-      new_psp(lr.DX, r->CS);
+      new_psp(lr.DX, cu_psp);
       break;
 
```

**Comment by stsp** [comment]
Darn, you posted it 1 second before I pushed that patch!

**Comment by stsp** [comment]
Yes, that's the right fix, thanks.
Unbelievable that 0x26 didn't work!

**Comment by andrewbird** [comment]
You have a better commit message!  Alpha Waves still doesn't work for me though!

**Comment by stsp** [comment]
Can you try by not zeroing PSP?

**Comment by andrewbird** [comment]
Sure, but I wonder if when the PSP is activated by function 0x50 it should be populated. In your PC-DOS PSP dump above was that before or after 0x50, because in my tests all the other DOSes zero it on 0x26?

**Comment by stsp** [comment]
The crash indeed happened _after_ 0x50, and
even after 0x30 where the corruption starts to
happen. But I added prints into a function `msdos()`
in int.c and IIRC was not seeing 0 even when 0x50
was just called. (but may be a wrong recollection)

**Comment by andrewbird** [comment]
Not zeroing allows the program to move on past the insert disk stage to this
![alpha1](https://user-images.githubusercontent.com/220835/69724346-a942ce80-1113-11ea-9a5e-923fd4976099.png)

**Comment by stsp** [comment]
Interesting.
Because w/o the patch we just did and with
not zeroing, I think it went even further - up
to setting the gfx mode.

**Comment by andrewbird** [comment]
Upon exit of that test I saw MCB corruption
~~~
dos mem corrupt, first_mcb=0292
prev 07e7:0000|4d f0 07 07 00 00 00 00 00 00 00 00 00 00 00 00 M≡..............
notMZ07ef:0000|20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00         ........
 
fdpp crashed.
Press any key to exit.
~~~

**Comment by stsp** [comment]
Maybe the prog corrupted it because
of the wrong PSP or something.
We need to get it working first.

**Comment by andrewbird** [comment]
With zeroing, by the time I get the 'no more handles error' the PSP appears to have a proper parent

~~~
dosdebug> d cs:0000
dosdebug> 

0d5a:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E7 F6 00 F0 0F F5  M . ..p~.pgv.p.u
0d5a:0010 00 F0 11 F5 00 F0 09 0D 01 01 01 00 02 FF FF FF  .p.u.p.......
0d5a:0020 FF FF FF FF FF FF FF FF FF FF FF FF 4A 0D E2 03  J.b.
0d5a:0030 09 0D 14 00 18 00 5A 0D 00 00 09 0D 00 00 00 00  ......Z.........
0d5a:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0d5a:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 00 B0 C0  M!K...........0@
0d5a:0060 B4 02 CD E6 72 08 B0 C1 B4 02 CD E6 00 00 B0 C0  4.Mfr.0A4.Mf..0@
0d5a:0070 B4 02 CD E6 72 08 B0 C1 B4 02 CD E6 00 00 00 00  4.Mfr.0A4.Mf....
~~~

if I look at the parent PSP
~~~
dosdebug> d 0d09:0000
dosdebug> 

0d09:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E7 F6 00 F0 0F F5  M . ..p~.pgv.p.u
0d09:0010 00 F0 11 F5 00 F0 F0 07 01 01 01 00 02 FF FF FF  .p.u.pp......
0d09:0020 FF FF FF FF FF FF FF FF FF FF FF FF F9 0C E2 01  y.b.
0d09:0030 01 0C 14 00 18 00 09 0D 00 00 F0 07 00 00 00 00  ..........p.....
0d09:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0d09:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
0d09:0060 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
0d09:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00          ........
dosdebug> mcbs
dosdebug> 

ADDR(LOW) PARAS  OWNER
0292:0000 0x04a9 [DOS]
  => ADDR      PARAS TYPE USAGE
     0293:0000 0x000c [F] Files
     02a0:0000 0x000a [D] Driver (EMUFS)
     02ab:0000 0x029e [B] Buffers
     054a:0000 0x00cf [F] Files
     061a:0000 0x008f [L] CDS Array
     06aa:0000 0x0080 [S] Stacks
     072b:0000 0x0010 [B] Buffers
073c:0000 ------ [LINK]
07e7:0000 0x0007 [FREE]
07ef:0000 0x0410 [COMMAND]
0c00:0000 0x00e6 [02032]
0ce7:0000 0x0010 [02032]
0cf8:0000 0x000f [03337]
0d08:0000 0x0040 [ALPHA]
0d49:0000 0x000f [03418]
0d59:0000 0x01bf [ALPHA_E]
0f19:0000 0x00f5 [03866]
100f:0000 0x8ff0 [FREE] (END)
~~~

**Comment by stsp** [comment]
You need to see it at the time of 0x31 call.
After that, it stash "creating" PSP at 0, and
maybe even properly, but... :)

**Comment by andrewbird** [comment]
After the PSP copy fix, the error from file open function 0x3d has changed from 'no more handles' to 'access denied'

~~~
0d5a:145e CD21             int  21                                              
dosdebug>                                                                       
dosdebug>                                                                       
INT 0x21, system state: emulated,stopped in real mode while in DPMI             
AX=3d00  BX=1b54  CX=c000  DX=1b54  SI=0d5a  DI=039f  SP=19b0  BP=091e          
DS=0d5a  ES=0d5a  FS=3131  GS=3532  FL=000b3246                                 
CS:IP=0d5a:146e       SS:SP=0d5a:19b0                                           
                                                                                
0d5a:146e CD21             int  21                                              
dosdebug> t                                                                     
dosdebug>                                                                       
system state: emulated,stopped in real mode while in DPMI                       
AX=0005  BX=1b54  CX=c000  DX=1b54  SI=0d5a  DI=039f  SP=19b0  BP=091e          
DS=0d5a  ES=0d5a  FS=3131  GS=3532  FL=00083346                                 
CS:IP=0d5a:1470       SS:SP=0d5a:19b0                                           
                                                                                
0d5a:1470 7203             jc   1475 ($+3)                                      
~~~

Tested with both FAT16 image and MFS, same result.

BTW dosdebug always seems to report 'stopped in real mode while in DPMI' now, though I don't think I'm running any DPMI program.

**Comment by stsp** [comment]
comcom32

**Comment by andrewbird** [comment]
Ahh, okay thanks.

**Comment by andrewbird** [comment]
I noticed that at the int21/3d call `cu_psp` is zero, so I wondered where else it gets set. I see that `return_user()` does set this and is called by int21/31 service. This is the line that's suspicious
https://github.com/stsp/fdpp/blob/425729abd915881b2ed06d15e5f679d4f7f73021/kernel/task.c#L566
Making it conditional on not being zero allowed program to get further, but I think someone that understands properly what's required here (@stsp) should look at this function closely.

**Comment by stsp** [comment]
It is exactly the function that
is called by 0x31 or 0x4c. It
gets to the parent psp which
is zero. You are back to the
beginning. :)

**Comment by andrewbird** [comment]
Yes and probably time to give up before I send myself mad!

**Comment by stsp** [comment]
But the question is simple: where
parent_psp became non-zero with
pc-dos, or, maybe, what are those
undocumented circumstances under
which 0x26 does not set it to zero.
With the above psp bugfix and with
recent iret tracing addition I am sure
we are armed enough to find an answer.

**Comment by andrewbird** [comment]
here's some log of pcdos 7.10
~~~
# now about to do 0x50 set PSP note parent is zero                              
                                                                                
INT 0x21, system state: emulated,stopped                                        
AX=5041  BX=1394  CX=0f30  DX=11d4  SI=0000  DI=0000  SP=19ac  BP=0000          
DS=13a4  ES=1498  FS=0000  GS=0000  FL=000b3202                                 
CS:IP=11d4:08a7       SS:SP=11d4:19ac                                           
                                                                                
11d4:08a7 CD21             int  21                                              
dosdebug> d bx:0000                                                             
dosdebug>                                                                       
                                                                                
1394:0000 CD 20 00 00 00 9A F0 FE 1D F0 F1 0E D4 11 AD 01  M ....p~.pq.T.-.     
1394:0010 41 10 85 15 D4 11 00 00 25 A1 7D 00 14 06 70 00  A...T...%!}...p.     
1394:0020 16 00 CC 0F 14 06 70 00 14 06 70 00 00 00 00 00  ..L...p...p.....     
1394:0030 00 00 14 00 18 00 94 13 FF FF FF FF 00 00 00 00  ............         
1394:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1394:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 00 00 00  M!K.............     
1394:0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1394:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
                                                                                
# now about to do 0x31 TSR - note parent is still zero, but PSP CD20 has been changed
INT 0x21, system state: emulated,stopped                                        
AX=3100  BX=0000  CX=0000  DX=00f5  SI=03c0  DI=0000  SP=0100  BP=0000          
DS=0000  ES=0000  FS=0000  GS=0000  FL=000b3206                                 
CS:IP=1394:1023       SS:SP=1394:0100                                           
                                                                                
1394:1023 CD21             int  21                                              
dosdebug> d cs:0000                                                             
dosdebug>                                                                       
                                                                                
1394:0000 5A 00 00 6B 8C 9A F0 FE 1D F0 F1 0E D4 11 AD 01  Z..k..p~.pq.T.-.     
1394:0010 41 10 85 15 D4 11 00 00 25 A1 7D 00 14 06 70 00  A...T...%!}...p.     
1394:0020 16 00 CC 0F 14 06 70 00 14 06 70 00 00 00 E2 00  ..L...p...p...b.     
1394:0030 94 13 14 00 18 00 94 13 FF FF FF FF 00 00 00 00  ............         
1394:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1394:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 00 00 00  M!K.............     
1394:0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
1394:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
                                                                                
# now about to do 0x4d get return code notice CS has changed and parent populated
INT 0x21, system state: emulated,stopped                                        
AX=4d00  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=19b0  BP=0000          
DS=0000  ES=0000  FS=0000  GS=0000  FL=000b7202                                 
CS:IP=11d4:0eff       SS:SP=11d4:19b0                                           
                                                                                
11d4:0eff CD21             int  21                                              
                                                                                
dosdebug> d cs:0000                                                             
dosdebug>                                                                       
                                                                                
11d4:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E7 F6 00 F0 AD 01  M . ..p~.pgv.p-.     
11d4:0010 41 10 B8 01 41 10 8A 11 01 01 01 00 02 FF FF FF  A.8.A........        
11d4:0020 FF FF FF FF FF FF FF FF FF FF FF FF CB 11 90 19  K...                 
11d4:0030 D4 11 14 00 18 00 D4 11 FF FF FF FF 00 00 00 00  T.....T.....         
11d4:0040 07 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................     
11d4:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 00 8C C3  M!K............C     
11d4:0060 CD 21 B8 00 30 CD 21 3D 00 00 00 00 00 00 8C C3  M!8.0M!=.......C     
11d4:0070 CD 21 B8 00 30 CD 21 3D 00 00 00 00 00 00 00 00  M!8.0M!=........     
                                                                                
#  see what's at parent address doesn't look like a PSP                          
dosdebug> d 11a8:0000                                                           
dosdebug>                                                                       
                                                                                
11a8:0000 21 BA 03 02 BB 15 02 B8 00 4B CD 21 2E 80 3E 13  !:..;..8.KM!..>.     
11a8:0010 02 01 74 0A 2E C5 16 56 01 B8 21 25 CD 21 B8 00  ..t..E.V.8!%M!8.     
11a8:0020 4C CD 21 41 4C 50 48 41 5F 45 2E 43 4F 4D 00 4D  LM!ALPHA_E.COM.M     
11a8:0030 6F 6B 21 01 00 00 00 80 00 8A 11 23 02 8A 11 23  ok!........#...#     
11a8:0040 02 8A 11 00 00 8C C3 CD 21 B8 00 30 CD 21 3D 07  ......CM!8.0M!=.     
11a8:0050 0A 74 11 BA 52 23 E8 30 FE 8C C0 26 39 06 16 00  .t.:R#h0~.@&9...     
11a8:0060 74 FE CD 20 BA 9F 28 B1 04 D3 EA 8C C8 03 C2 A3  t~M :.(1.Sj.H.B#     
11a8:0070 7E 22 E8 94 08 E8 DF 0A B8 00 B7 CD 2F 3C 00 74  ~"h..h_.8.7M/<.t     
~~~

**Comment by stsp** [comment]
Interesting.
I can swear I've seen non-zero psp,
but lets assume I was sleeping.
So if what you see is true, then how
about a simple trick: in case of zero
parent, try to use return CS as psp?
Looks exactly like what you describe
above.

**Comment by andrewbird** [comment]
have to go out now, will try later

**Comment by stsp** [comment]
> try to use return CS as psp?

But it won't work for the same reason it
didn't work for 0x26 - we don't have a
caller's cs. So I don't think zeroed parent
can actually be recovered.

**Comment by stsp** [comment]
> With the above psp bugfix and with
> recent iret tracing addition I am sure
> we are armed enough

No because the iret tracing itself breaks it.

**Comment by stsp** [comment]
Please apply this patch:
```
diff --git a/src/base/bios/x86/bios.s b/src/base/bios/x86/bios.s
index 8ec8fcf02..bfc5ed9bb 100644
--- a/src/base/bios/x86/bios.s
+++ b/src/base/bios/x86/bios.s
@@ -896,7 +896,7 @@ int_rvc_ret_cs_\inum:
        popl %eax
        jnz 9f                  /* handled */
        jc 2f                   /* second_revect */
-.if 0x\inum == 0x2f            /* int2f uses stack exchange */
+.if 0x\inum == 0x2f || 0x\inum == 0x21         /* int2f uses stack exchange */
        ljmp *%cs:int_rvc_data_\inum
 .else
        pushfw
diff --git a/src/base/core/int.c b/src/base/core/int.c
index e615e37ad..3d053d4fc 100644
--- a/src/base/core/int.c
+++ b/src/base/core/int.c
@@ -1560,6 +1560,10 @@ static int msdos(void)
            can_change_title = 0;
            return 0;
        }
+case 0x50: {
+struct PSP *psp = SEG2UNIX(_BX);
+error("parent %x\n", psp->parent_psp);
+}
     }
     return 0;
 }
```

You'll quickly see that PSP is not zero with PC-DOS.
That patch also disables iret tracing.

**Comment by andrewbird** [comment]
So is the new code run before or after the real pcdos int21/50? If it's after (my dosdebug above is just before showing zero) perhaps int21/50 populates it?

with PC-DOS 7.10
~~~
ERROR: parent 0
ERROR: parent 8d5b
ERROR: parent 8d5b
ERROR: parent 118a
ERROR: parent 118a
ERROR: parent 118a
ERROR: parent 118a
~~~

**Comment by stsp** [comment]
It runs before.
There is a 0x4b hook that alters
windows file names. It wouldn't work after.

**Comment by andrewbird** [comment]
So at least initially it was zero, and we still don't know how it got populated from there.

**Comment by stsp** [comment]
I don't think it was.
My testing shows the opposite.

**Comment by stsp** [comment]
I disassembled the 0x26 func in PC-DOS
and I don't see parent zeroing there.

**Comment by andrewbird** [comment]
My test case showed that it was zero from int21/26 for all DOSes but there could be something wrong with it, so quite the mystery.

Have you looked at the DR-DOS 7.01 open source release? int21 functions 26 and 55 seem to do the opposite to their rbil descriptions regarding psp->parent
[int21/26](http://www.ctyme.com/intr/rb-2682.htm)
[int21/55](http://www.ctyme.com/intr/rb-2989.htm)

See `func26` & `func55`in `drdos/process.a86` I think you can get it from sourceforge

**Comment by stsp** [comment]
No, but disasm I have, is quite clear anyway.
I think not zeroing is the right thing to do, and
the next problem here is that this func calls
0x48 with 0 in DX and then uses the result.
Trying to find what that can be.

**Comment by stsp** [comment]
I applied more fixes.
Much better now, the game is playable.

**Comment by stsp** [comment]
Mm, the `cu_psp` change became needed
only after the iret tracing change. And other
DOSes still had `cd20` only because they
update most fields manually, including that
one, but PSP was still wrong.
I'll likely need to revert it.

**Comment by stsp** [comment]
I repaired the pc-dos breakage.
Now whether to revert the `cu_psp`
change is what I don't know.
It doesn't look like it can hurt, but
its not what other DOSes do.
What do you think?

**Comment by andrewbird** [comment]
Is is okay if I post a link to OpenDOS here?

**Comment by stsp** [comment]
You may have seen the zero parent
because of the iret tracing patch. It
was copying the psp out of nowhere.
But pc-dos recreates most fields
manually, so it still looks like a real psp!
I think Ralf Brown was cheated the
same way: he was probably using
some debugger, or maybe some tsr
that hooks int21. Even though he knew
0x26 uses CS, he probably missed
the implications we found, exactly
because the DOSes make that psp
the way it looks still valid, but freedos
(rightly IMO) doesn't fo this.
Can we report a bug to rbil? :)

**Comment by stsp** [comment]
Please do, I dont know its license,
but I wont care about a link.

**Comment by stsp** [comment]
But nothe that opendos et al could
have been tricked by rbil. We need
to test alpha waves there, and I bet
it wont work.

**Comment by andrewbird** [comment]
I'm thinking more about the comment regarding CS; it directly contradicts us using cu_psp, but suggests our intention of it needing to be the user's CS is correct.
https://github.com/the-grue/OpenDOS/blob/e8be6acdf8bdaa10ba87e98e789d3762515fb345/IBMDOS/PROCESS.A86#L124-L143

**Comment by andrewbird** [comment]
So Alphawaves is looking a lot better on FDPP now, enough to run the demo anyway. I do see a corrupted vertically scrolling image immediately on entering the game, and it also hangs dosemu on exit, bu only after the game has been entered.

**Comment by stsp** [comment]
IBMDOS? So is this a pc-dos after all?
Yes, I see it using CS, and no I dont
see it zeroing parent_psp.

Is the exit crash specific to fdpp?

**Comment by andrewbird** [comment]
Pretty sure about that IBMDOS directory being named so is because the target file is called 'ibmdos.com', it's certainly DR-DOS based.

I find this comment most interesting,
~~~
Get pointer to INT 21 structure of IP/CS/Flags and get the USER CS this is used as 
the PSP for this function call and NOT current_psp.
~~~
so if we shouldn't use `cu_psp` as the source segment for the copy, somehow we still need to get the user's real CS. 

Doesn't seem to be just FDPP, I ran it on PCDOS 7.10 with gdb and got this on exit
~~~
ERROR: bad dos helper function: AX=0x4649
ERROR: EMU86: error 2
~~~

**Comment by stsp** [comment]
We can or can't get the real user's cs,
depending on who hooks int21 and how.
The biggest problem is that we never
know if the CS we got, is what we need.
If you want to intercept iret of int21,
you need to exclude 0x26 so that dos
can get a valid cs... I'd say its a mess,
and using cu_psp is the right thing
to do, but...

**Comment by andrewbird** [comment]
Just for completeness I ran my testcase on several DOSes and it seems your latest fixes changed something. Now only FreeDOS 1.00, 1.10 and 1.20 zero the PSP parent whereas MSDOS 6.22, PCDOS 7.10, DRDOS 7.01 and FDPP don't.

To see what the new PSP looked like I ran MS-DOS 6.22 with the testcase under dosdebug. Now it seems to me that I'm seeing the effect you did earlier when running with dosdebug, in that the copy source is incorrect and only the explicitly set fields are valid. It's a little unsettling that using dosdebug can change things?

But I noticed the crap only occurs if I `t` over the interrupt
~~~
dosdebug> d dx:0000
dosdebug> 

122f:0000 CD 20 F4 F4 F4 9A F0 FE 1D F0 E8 F6 00 F0 4A 01  M ttt.p~.phv.pJ.
122f:0010 E3 0E 55 01 E3 0E F4 F4 D2 B0 D9 B2 32 A5 4A AA  c.U.c.ttR0Y22%J*
122f:0020 AB A9 A9 AE 0D 44 B5 40 0A 4D C1 40 F4 F4 F4 F4  +))..D5@.MA@tttt
122f:0030 F4 F4 14 00 18 00 2F 12 FF FF FF FF F4 F4 F4 F4  tt..../.tttt
122f:0040 06 16 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  ..tttttttttttttt
122f:0050 CD 21 CB F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  M!Kttttttttttttt
122f:0060 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  tttttttttttttttt
122f:0070 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4 F4  tttttttttttttttt
~~~

if I `ti` into it the result is good
~~~
004e:4236 07               pop  es
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=26f0  BX=0000  CX=0000  DX=122f  SI=0000  DI=0000  SP=fff8  BP=0000
DS=102f  ES=122f  FS=0000  GS=0000  FL=00133346
CS:IP=004e:4237       SS:SP=102f:fff8

004e:4237 CF               iret
dosdebug> 
dosdebug> 
system state: emulated,stopped
AX=26f0  BX=0000  CX=0000  DX=122f  SI=0000  DI=0000  SP=fffe  BP=0000
DS=102f  ES=122f  FS=0000  GS=0000  FL=00083302
CS:IP=102f:010e       SS:SP=102f:fffe

102f:010e BF0000           mov  di,0000
dosdebug> d dx:0
dosdebug> 

122f:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E8 F6 00 F0 4A 01  M . ..p~.phv.pJ.
122f:0010 E3 0E 55 01 E3 0E E3 0E 01 01 01 00 02 FF FF FF  c.U.c.c......
122f:0020 FF FF FF FF FF FF FF FF FF FF FF FF 25 10 E6 FF  %.f
122f:0030 2F 10 14 00 18 00 2F 12 FF FF FF FF 00 00 00 00  /...../.....
122f:0040 06 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
122f:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
122f:0060 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
122f:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00          ........
~~~

Helpful?

**Comment by stsp** [comment]
This is because earlier you did the
patch that catches `retf 2` from
interrupt. Please exclude the ints
21,28,2f,33 from that machinery
and things be well.

**Comment by andrewbird** [comment]
This one  https://github.com/stsp/dosemu2/commit/158fe96f8f4 ?

**Comment by stsp** [comment]
Yes.

**Comment by andrewbird** [comment]
Adding this gives the correct results, but of course the overrunning of the following instruction is back
```c
diff --git a/src/plugin/debugger/mhpdbgc.c b/src/plugin/debugger/mhpdbgc.c
index 11a2ad0ad..e7b0854dc 100644
--- a/src/plugin/debugger/mhpdbgc.c
+++ b/src/plugin/debugger/mhpdbgc.c
@@ -840,6 +840,8 @@ static void mhp_trace(int argc, char *argv[])
     switch (csp[0]) {
       case 0xcd:
         if (mhpdbgc.trapcmd != 1) { // plain 't'
+          if (csp[1] == 0x21 || csp[1] == 0x2f || csp[1] == 0x28 || csp[1] == 0x33)
+            break;
           LWORD(eip) += 2;
           trace_stack_push(_CS, _IP);
```

~~~
AX=2600  BX=0000  CX=0000  DX=122f  SI=0000  DI=0000  SP=fffe  BP=0000
DS=102f  ES=122f  FS=0000  GS=0000  FL=000b3302
CS:IP=102f:010c       SS:SP=102f:fffe

102f:010c CD21             int  21
dosdebug> t
dosdebug> 
system state: emulated,stopped
AX=26f0  BX=0000  CX=0000  DX=122f  SI=0000  DI=0000  SP=fffe  BP=0000
DS=102f  ES=122f  FS=0000  GS=0000  FL=000b3302
CS:IP=102f:0111       SS:SP=102f:fffe

102f:0111 26813DCD20       cmp  word es:[di],20CD
dosdebug> u 102f:010c
dosdebug> 

102f:010c CD21             int  21
102f:010e BF0000           mov  di,0000
102f:0111 26813DCD20       cmp  word es:[di],20CD
102f:0116 750C             jne  0124 ($+c)
102f:0118 26837D1600       cmp  word es:[di+16],0000
102f:011d 750A             jne  0129 ($+a)
102f:011f BA7001           mov  dx,0170
102f:0122 EB0A             jmp  short 012E ($+a)
102f:0124 BA3601           mov  dx,0136
102f:0127 EB05             jmp  short 012E ($+5)
102f:0129 BA5701           mov  dx,0157
dosdebug> d dx:0
dosdebug> 

122f:0000 CD 20 00 A0 00 9A F0 FE 1D F0 E8 F6 00 F0 4A 01  M . ..p~.phv.pJ.
122f:0010 E3 0E 55 01 E3 0E E3 0E 01 01 01 00 02 FF FF FF  c.U.c.c......
122f:0020 FF FF FF FF FF FF FF FF FF FF FF FF 25 10 E6 FF  %.f
122f:0030 2F 10 14 00 18 00 2F 12 FF FF FF FF 00 00 00 00  /...../.....
122f:0040 06 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
122f:0050 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
122f:0060 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
122f:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 00 00 00          ........
dosdebug> 
~~~

Any other way to reimplement?

**Comment by stsp** [comment]
Many of them, with various limitations.
Add breakpoint, or exclude just the
problematic ones, like 0x26, or just
detect the over-run and print the
missing instruction, or try to catch
iret at VM86_STI or... plenty of ways.
Lets stick to something simple.

**Comment by stsp** [comment]
Or, more likely, nothing should be done but
to find out why the debugger is not pinged
after `do_int_iret()`.

**Comment by stsp** [comment]
In fact, it seems to work for me:
```
2bed:0040 CD21             int  21
dosdebug> t
dosdebug> 
system state: emulated,stopped in real mode while in DPMI
AX=2c01  BX=339c  CX=1116  DX=193a  SI=0030  DI=4d0e  SP=4ab8  BP=4ab8
DS=339c  ES=62e6  FS=7461  GS=220a  FL=000b7302
CS:IP=2bed:0042       SS:SP=3f32:4ab8

2bed:0042 32E4             xor  ah,ah
dosdebug> 
```

40 and 42 are adjacent addresses.

**Comment by stsp** [comment]
Sorry, was in a hurry, tried w/o your changes.
But anyway, `do_int_iret()` should be investigated.
Some debugger hook is missing somewhere.

**Comment by andrewbird** [comment]
So should I do a PR for the fix above, then look at `do_int_iret()`, as I don't think it should stay as now since we get wrong DOS execution?

**Comment by stsp** [comment]
Good plan, will apply in a few days.

**Comment by stsp** [comment]
I am not sure 9c4a468 was correct.
Andrew, you seem to have a PSP test,
could you please check if file table
pointer at offset 0x34 copied or updated
by int21/26h?

**Comment by stsp** [comment]
Related to #184
